# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA_Projects/MicroBlaze_Uart_Gpio/MicroBlaze_Uart_Gpio.srcs/sources_1/bd/MicroBlaze_Uart_Gpio/ip/MicroBlaze_Uart_Gpio_ilmb_v10_0/MicroBlaze_Uart_Gpio_ilmb_v10_0.xci
# IP: The module: 'MicroBlaze_Uart_Gpio_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_Projects/MicroBlaze_Uart_Gpio/MicroBlaze_Uart_Gpio.srcs/sources_1/bd/MicroBlaze_Uart_Gpio/ip/MicroBlaze_Uart_Gpio_ilmb_v10_0/MicroBlaze_Uart_Gpio_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_Uart_Gpio_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA_Projects/MicroBlaze_Uart_Gpio/MicroBlaze_Uart_Gpio.srcs/sources_1/bd/MicroBlaze_Uart_Gpio/ip/MicroBlaze_Uart_Gpio_ilmb_v10_0/MicroBlaze_Uart_Gpio_ilmb_v10_0.xci
# IP: The module: 'MicroBlaze_Uart_Gpio_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_Projects/MicroBlaze_Uart_Gpio/MicroBlaze_Uart_Gpio.srcs/sources_1/bd/MicroBlaze_Uart_Gpio/ip/MicroBlaze_Uart_Gpio_ilmb_v10_0/MicroBlaze_Uart_Gpio_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MicroBlaze_Uart_Gpio_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
