# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sgeuser30/Desktop/vybhav/FPGA/shared_memory/shared_bram/shared_bram.srcs/sources_1/bd/shared_bram/ip/shared_bram_rst_ps7_0_100M_0/shared_bram_rst_ps7_0_100M_0.xci
# IP: The module: 'shared_bram_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sgeuser30/Desktop/vybhav/FPGA/shared_memory/shared_bram/shared_bram.srcs/sources_1/bd/shared_bram/ip/shared_bram_rst_ps7_0_100M_0/shared_bram_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'shared_bram_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/sgeuser30/Desktop/vybhav/FPGA/shared_memory/shared_bram/shared_bram.srcs/sources_1/bd/shared_bram/ip/shared_bram_rst_ps7_0_100M_0/shared_bram_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'shared_bram_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/sgeuser30/Desktop/vybhav/FPGA/shared_memory/shared_bram/shared_bram.srcs/sources_1/bd/shared_bram/ip/shared_bram_rst_ps7_0_100M_0/shared_bram_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shared_bram_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/sgeuser30/Desktop/vybhav/FPGA/shared_memory/shared_bram/shared_bram.srcs/sources_1/bd/shared_bram/ip/shared_bram_rst_ps7_0_100M_0/shared_bram_rst_ps7_0_100M_0.xci
# IP: The module: 'shared_bram_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sgeuser30/Desktop/vybhav/FPGA/shared_memory/shared_bram/shared_bram.srcs/sources_1/bd/shared_bram/ip/shared_bram_rst_ps7_0_100M_0/shared_bram_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'shared_bram_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/sgeuser30/Desktop/vybhav/FPGA/shared_memory/shared_bram/shared_bram.srcs/sources_1/bd/shared_bram/ip/shared_bram_rst_ps7_0_100M_0/shared_bram_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'shared_bram_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/sgeuser30/Desktop/vybhav/FPGA/shared_memory/shared_bram/shared_bram.srcs/sources_1/bd/shared_bram/ip/shared_bram_rst_ps7_0_100M_0/shared_bram_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shared_bram_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
