# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA_Projects/arty_uart_calculator/arty_uart_calculator.srcs/sources_1/bd/arty_uart_calculator/ip/arty_uart_calculator_dlmb_bram_if_cntlr_0/arty_uart_calculator_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'arty_uart_calculator_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_Projects/arty_uart_calculator/arty_uart_calculator.srcs/sources_1/bd/arty_uart_calculator/ip/arty_uart_calculator_dlmb_bram_if_cntlr_0/arty_uart_calculator_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_uart_calculator_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA_Projects/arty_uart_calculator/arty_uart_calculator.srcs/sources_1/bd/arty_uart_calculator/ip/arty_uart_calculator_dlmb_bram_if_cntlr_0/arty_uart_calculator_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'arty_uart_calculator_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_Projects/arty_uart_calculator/arty_uart_calculator.srcs/sources_1/bd/arty_uart_calculator/ip/arty_uart_calculator_dlmb_bram_if_cntlr_0/arty_uart_calculator_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_uart_calculator_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
