# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/shared_bram/shared_bram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram || ORIG_REF_NAME==shared_bram} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_processing_system7_0_0/shared_bram_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_processing_system7_0_0 || ORIG_REF_NAME==shared_bram_processing_system7_0_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_microblaze_0_0/shared_bram_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_microblaze_0_0 || ORIG_REF_NAME==shared_bram_microblaze_0_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_dlmb_v10_0/shared_bram_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_dlmb_v10_0 || ORIG_REF_NAME==shared_bram_dlmb_v10_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_ilmb_v10_0/shared_bram_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_ilmb_v10_0 || ORIG_REF_NAME==shared_bram_ilmb_v10_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_dlmb_bram_if_cntlr_0/shared_bram_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==shared_bram_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_ilmb_bram_if_cntlr_0/shared_bram_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==shared_bram_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_lmb_bram_0/shared_bram_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_lmb_bram_0 || ORIG_REF_NAME==shared_bram_lmb_bram_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_mdm_1_0/shared_bram_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_mdm_1_0 || ORIG_REF_NAME==shared_bram_mdm_1_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_rst_ps7_0_100M_0/shared_bram_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_rst_ps7_0_100M_0 || ORIG_REF_NAME==shared_bram_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_axi_bram_ctrl_0_0/shared_bram_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_axi_bram_ctrl_0_0 || ORIG_REF_NAME==shared_bram_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_blk_mem_gen_0_0/shared_bram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_blk_mem_gen_0_0 || ORIG_REF_NAME==shared_bram_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_xbar_0/shared_bram_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_xbar_0 || ORIG_REF_NAME==shared_bram_xbar_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_axi_interconnect_0_0/shared_bram_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_axi_interconnect_0_0 || ORIG_REF_NAME==shared_bram_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_xbar_1/shared_bram_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_xbar_1 || ORIG_REF_NAME==shared_bram_xbar_1} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_axi_interconnect_0_1/shared_bram_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_axi_interconnect_0_1 || ORIG_REF_NAME==shared_bram_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_axi_interconnect_0_2/shared_bram_axi_interconnect_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_axi_interconnect_0_2 || ORIG_REF_NAME==shared_bram_axi_interconnect_0_2} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_axi_gpio_0_2/shared_bram_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_axi_gpio_0_2 || ORIG_REF_NAME==shared_bram_axi_gpio_0_2} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_axi_gpio_0_3/shared_bram_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_axi_gpio_0_3 || ORIG_REF_NAME==shared_bram_axi_gpio_0_3} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_auto_pc_0/shared_bram_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_auto_pc_0 || ORIG_REF_NAME==shared_bram_auto_pc_0} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_auto_pc_1/shared_bram_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_auto_pc_1 || ORIG_REF_NAME==shared_bram_auto_pc_1} -quiet] -quiet

# IP: bd/shared_bram/ip/shared_bram_auto_pc_2/shared_bram_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shared_bram_auto_pc_2 || ORIG_REF_NAME==shared_bram_auto_pc_2} -quiet] -quiet

# XDC: bd/shared_bram/shared_bram_ooc.xdc
