# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# Block Designs: bd/arty_uart_calculator/arty_uart_calculator.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator || ORIG_REF_NAME==arty_uart_calculator} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_microblaze_0_0/arty_uart_calculator_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_microblaze_0_0 || ORIG_REF_NAME==arty_uart_calculator_microblaze_0_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_dlmb_v10_0/arty_uart_calculator_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_dlmb_v10_0 || ORIG_REF_NAME==arty_uart_calculator_dlmb_v10_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_ilmb_v10_0/arty_uart_calculator_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_ilmb_v10_0 || ORIG_REF_NAME==arty_uart_calculator_ilmb_v10_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_dlmb_bram_if_cntlr_0/arty_uart_calculator_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==arty_uart_calculator_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_ilmb_bram_if_cntlr_0/arty_uart_calculator_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==arty_uart_calculator_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_lmb_bram_0/arty_uart_calculator_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_lmb_bram_0 || ORIG_REF_NAME==arty_uart_calculator_lmb_bram_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_xbar_0/arty_uart_calculator_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_xbar_0 || ORIG_REF_NAME==arty_uart_calculator_xbar_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_microblaze_0_axi_periph_0/arty_uart_calculator_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_microblaze_0_axi_periph_0 || ORIG_REF_NAME==arty_uart_calculator_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_microblaze_0_axi_intc_0/arty_uart_calculator_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_microblaze_0_axi_intc_0 || ORIG_REF_NAME==arty_uart_calculator_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_microblaze_0_xlconcat_0/arty_uart_calculator_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_microblaze_0_xlconcat_0 || ORIG_REF_NAME==arty_uart_calculator_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_mdm_1_0/arty_uart_calculator_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_mdm_1_0 || ORIG_REF_NAME==arty_uart_calculator_mdm_1_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_clk_wiz_1_0/arty_uart_calculator_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_clk_wiz_1_0 || ORIG_REF_NAME==arty_uart_calculator_clk_wiz_1_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_rst_clk_wiz_1_100M_0/arty_uart_calculator_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==arty_uart_calculator_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_reset_inv_0_0/arty_uart_calculator_reset_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_reset_inv_0_0 || ORIG_REF_NAME==arty_uart_calculator_reset_inv_0_0} -quiet] -quiet

# IP: bd/arty_uart_calculator/ip/arty_uart_calculator_axi_uartlite_0_0/arty_uart_calculator_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_uart_calculator_axi_uartlite_0_0 || ORIG_REF_NAME==arty_uart_calculator_axi_uartlite_0_0} -quiet] -quiet

# XDC: bd/arty_uart_calculator/arty_uart_calculator_ooc.xdc
