# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# Block Designs: bd/MicroBlaze_Uart/MicroBlaze_Uart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart || ORIG_REF_NAME==MicroBlaze_Uart} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_microblaze_0_0/MicroBlaze_Uart_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_microblaze_0_0 || ORIG_REF_NAME==MicroBlaze_Uart_microblaze_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_dlmb_v10_0/MicroBlaze_Uart_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_dlmb_v10_0 || ORIG_REF_NAME==MicroBlaze_Uart_dlmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_ilmb_v10_0/MicroBlaze_Uart_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_ilmb_v10_0 || ORIG_REF_NAME==MicroBlaze_Uart_ilmb_v10_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_dlmb_bram_if_cntlr_0/MicroBlaze_Uart_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlaze_Uart_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_ilmb_bram_if_cntlr_0/MicroBlaze_Uart_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MicroBlaze_Uart_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_lmb_bram_0/MicroBlaze_Uart_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_lmb_bram_0 || ORIG_REF_NAME==MicroBlaze_Uart_lmb_bram_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_xbar_0/MicroBlaze_Uart_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_xbar_0 || ORIG_REF_NAME==MicroBlaze_Uart_xbar_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_microblaze_0_axi_periph_0/MicroBlaze_Uart_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MicroBlaze_Uart_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_microblaze_0_axi_intc_0/MicroBlaze_Uart_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MicroBlaze_Uart_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_microblaze_0_xlconcat_0/MicroBlaze_Uart_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_microblaze_0_xlconcat_0 || ORIG_REF_NAME==MicroBlaze_Uart_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_mdm_1_0/MicroBlaze_Uart_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_mdm_1_0 || ORIG_REF_NAME==MicroBlaze_Uart_mdm_1_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_clk_wiz_1_0/MicroBlaze_Uart_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_clk_wiz_1_0 || ORIG_REF_NAME==MicroBlaze_Uart_clk_wiz_1_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_rst_clk_wiz_1_100M_0/MicroBlaze_Uart_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MicroBlaze_Uart_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_reset_inv_0_0/MicroBlaze_Uart_reset_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_reset_inv_0_0 || ORIG_REF_NAME==MicroBlaze_Uart_reset_inv_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_Uart/ip/MicroBlaze_Uart_axi_uartlite_0_0/MicroBlaze_Uart_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_Uart_axi_uartlite_0_0 || ORIG_REF_NAME==MicroBlaze_Uart_axi_uartlite_0_0} -quiet] -quiet

# XDC: bd/MicroBlaze_Uart/MicroBlaze_Uart_ooc.xdc
